#!/bin/bash


aws ec2 run-instances \
  --image-id ami-0c02fb55956c7d316 \
  --count 1 \
  --instance-type t2.micro \
  --subnet-id subnet-0a1b2c3d4e5f6g7h8 \
  --associate-public-ip-address \
  --security-groups "default" \
  --key-name my-ec2-keypair \
  --user-data file://install-httpd.sh \
  --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value="WebServer"}]'

